// Generated by CoffeeScript 1.4.0

goog.provide("bindings");

$(document).on("focus", "#inputArtist", function() {
  $(this).val("");
  return $(this).css({
    color: "#000000"
  });
});

$(document).on("keypress", "#inputArtist", function(e) {
  if (e.which === 13) {
    return window.location = "#!/artists/search/name:" + $(this).val() + "/";
  }
});

$(document).on("click", "#submitButton", function() {
  return window.location = "#!/artists/search/name:" + $("#inputArtist").val() + "/";
});
