// Generated by CoffeeScript 1.4.0
var Artists;

goog.provide("controller.artists");

Artists = (function() {

  Artists.prototype.artist = null;

  function Artists(name) {
    this.name = name;
    if (Artist && this.artist === null) {
      this.artist = new Artist("Search");
    }
  }

  Artists.prototype.search = function(args) {
    return this.artist.getArtistImages(args.name, function(data) {
      return FRAMES.core.renderView(data);
    });
  };

  return Artists;

})();
