// Generated by CoffeeScript 1.4.0

goog.provide("FRAMES.dependencies");

/*
  For any script that can't be converted to coffeescript and needs to be outside the closure compiler. Load it here.
  Or for any file you havnen't had time to convert to coffeescript to be included in the compiler at a later time.
*/


(function($) {
  var js_array;
  js_array = [goog.basePath + "frames_depends/handlebars.js", goog.basePath + "frames_depends/underscore.js"];
  return $.each(js_array, function(i, o) {
    var script;
    script = document.createElement("script");
    script.type = "text/javascript";
    script.src = o;
    $("head").append(script);
    if (i === js_array.length) {
      return $.PubSub('dependsFinished').publish();
    }
  });
})(jQuery);
