// Generated by CoffeeScript 1.4.0
/*
main.coffee - Primary entry point
*/

goog.provide("FRAMES");

goog.require("FRAMES.dependencies");

goog.require("FRAMES.location");

goog.require("FRAMES.core");

goog.require("FRAMES.helpers");

goog.require("bindings");

goog.require("controller.artists");

goog.require("model.artist");

$(document).ready(function() {
  return FRAMES.core.parseURL();
});

$(window.location).bind("change", function() {
  return FRAMES.core.parseURL();
});
