// Generated by CoffeeScript 1.4.0
var Pages;

goog.provide("FRAMES.controller.pages");

Pages = (function() {

  Pages.prototype.page = null;

  function Pages(name) {
    this.name = name;
    if (Page && this.page === null) {
      this.page = new Page("Page");
    }
  }

  Pages.prototype.index = function(args) {
    var _data;
    _data = this.page.setData();
    return FRAMES.core.renderView(_data);
  };

  Pages.prototype.about = function(args) {
    var _data;
    _data = this.page.setData();
    return FRAMES.core.renderView(_data);
  };

  return Pages;

})();
