// Generated by CoffeeScript 1.4.0

goog.provide("FRAMES.helpers");

FRAMES.helpers = {
  capitalizeFirstLetter: function(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
  }
};
