// Generated by CoffeeScript 1.4.0
/*
main.coffee - Primary entry point
*/

goog.provide("FRAMES");

goog.require("FRAMES.dependencies");

goog.require("FRAMES.location");

goog.require("FRAMES.controller.pages");

goog.require("FRAMES.model.page");

goog.require("FRAMES.core");

goog.require("FRAMES.helpers");

$(document).ready(function() {
  return FRAMES.core.parseURL();
});

$(window.location).bind("change", function() {
  return FRAMES.core.parseURL();
});
